张量
=======
张量是一种专门的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量来编码模型的输入和输出，以及模型的参数。

张量类似于 NumPy 的 ndarrays，但张量可以在 GPU 或其他专用硬件上运行以加速计算。


In [ ]:
import torch
import numpy as np

张量初始化
=====================
**直接从数据中创建**

可以从数据直接创建张量，数据类型会自动推断。


In [105]:
data=[[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**从 NumPy 数组创建**

可以从 NumPy 数组创建张量（反之亦然）


In [106]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np = torch.tensor(np_array) # 也可以
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**从另一个张量创建**

新张量会保留参数张量的属性（形状、数据类型），除非显式覆盖。

In [107]:
x_ones= torch.ones_like(x_data) # 保留属性和形状
x_ones

tensor([[1, 1],
        [1, 1]])

In [108]:
x_rand = torch.rand_like(x_data,dtype=torch.float) # 覆盖属性
x_rand

# 传入张量的必须是浮点型 check_uniform_bounds" not implemented for 'Long

tensor([[0.8906, 0.3404],
        [0.1894, 0.0731]])

**使用随机值或常数值创建**

shape 是张量维度的元组。在下面的函数中，它决定输出张量的维度。


In [109]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6359, 0.8740, 0.3629],
        [0.3827, 0.1323, 0.5446]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


张量属性
=================

张量属性描述了它们的形状、数据类型和存储它们的设备。

In [110]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


张量操作
=================

100 多种张量操作，包括转置、索引、切片、数学运算、线性代数、随机采样等等，在 文档 有详细的介绍。

它们中的每一个都可以运行在 GPU 上（通常比 CPU 上的速度更快）。


In [111]:
# 移动张量到GPU
if torch.cuda.is_available():
    tensor=tensor.to('cuda')
tensor.device

device(type='cuda', index=0)

尝试一些列表中的操作。如果您熟悉 NumPy API，您会发现 Tensor API 非常容易使用。


**标准 NumPy 式索引和切片**


In [112]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


连接张量 可以使用 torch.cat 在给定维度上连接张量序列。另见 torch.stack，另一个与 torch.cat 略有不同的张量连接操作。


In [113]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**张量乘法**
逐个元素相乘


In [114]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


这计算两个张量之间的矩阵乘法。

In [115]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**就地操作** 具有 _ 后缀的操作是就地操作。例如：x.copy_(y)、x.t_() 将改变 x。


In [116]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

# 相当于instead

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>注意</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>就地操作可以节省一些内存，但由于会立即丢失历史记录，因此在计算导数时可能会出现问题。因此，不建议使用。</p>

</div>



------------------------------------------------------------------------


与 NumPy 的桥梁
=================

CPU 上的张量和 NumPy 数组可以共享其底层内存位置，更改一个将更改另一个。


张量到 NumPy 数组
=====================


In [117]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# 相当于相互变身呗

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


更改张量导致numpy变化


In [118]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy 数组到张量
=====================


In [119]:
n = np.ones(5)
print(n)
t = torch.from_numpy(n)
print(t)

# 相当于相互变身呗

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


通过改变numpy 从而改变张量


In [120]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

# 相当于一个人的不同形态，而n和t则是相对应的引用或者叫别名，并不是重新复制的副本

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
